/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import javax.swing.JOptionPane;

/**
 *
 * @author usuari
 */
public class interfaz2 extends javax.swing.JFrame {

    /**
     * Creates new form interfaz2
     */
    public interfaz2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INTRUCCIONES = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        sesion = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        regreso = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVERSIONES: LA LLEGADA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        INTRUCCIONES.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        INTRUCCIONES.setForeground(new java.awt.Color(255, 255, 255));
        INTRUCCIONES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User2.png"))); // NOI18N
        INTRUCCIONES.setText("INGRESE SU USUARIO Y COTRASEÑA PARA INGRESAR AL SISTEMA");
        getContentPane().add(INTRUCCIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 100, 630, -1));

        usuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("USUARIO:");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        contraseña.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("CONTRASEÑA: ");
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 310, -1));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 310, -1));

        sesion.setBackground(new java.awt.Color(0, 102, 204));
        sesion.setForeground(new java.awt.Color(255, 255, 255));
        sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Checkmark.png"))); // NOI18N
        sesion.setText("INICIAR SESION");
        sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sesionMouseClicked(evt);
            }
        });
        sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionActionPerformed(evt);
            }
        });
        getContentPane().add(sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 190, -1));

        salir.setBackground(new java.awt.Color(204, 0, 0));
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Error.png"))); // NOI18N
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 100, -1));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("INVERSIONES: LA LLEGADA");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        regreso.setBackground(new java.awt.Color(204, 0, 0));
        regreso.setForeground(new java.awt.Color(255, 255, 255));
        regreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Button_Rewind.png"))); // NOI18N
        regreso.setText("ATRAS");
        regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresoActionPerformed(evt);
            }
        });
        getContentPane().add(regreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/241688__astana-bike-astana-kazakhstan-cycling-the-best-team-claude-kloden_p.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void regresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresoActionPerformed
        interfaz obj=new interfaz();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_regresoActionPerformed

    private void sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sesionMouseClicked

    }//GEN-LAST:event_sesionMouseClicked

    private void sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionActionPerformed
        String Usuario= "admin";
        String Clave= "ciclo";
        
        String pass=new String(txtPass.getPassword());
        String user=new String(txtUser.getText());
        
        if(user.equals(Usuario) && pass.equals(Clave)){
            
            accesos2 acc= new accesos2();
            acc.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "El usuario y/o la Contraseña son incorresctos");
        }
    }//GEN-LAST:event_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel INTRUCCIONES;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton regreso;
    private javax.swing.JButton salir;
    private javax.swing.JButton sesion;
    private javax.swing.JLabel titulo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
