/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author usuari
 */
public class Ventas_producto extends javax.swing.JFrame {

    /**
     * Creates new form Ventas_producto
     */
    public Ventas_producto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bienvenida = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jRetorno = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        accion = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVERSIONES: LA LLEGADA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvenida.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        Bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        Bienvenida.setText("SISTEMA DE INVENTARIO");
        getContentPane().add(Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 330, 30));

        nombre.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("INVERSIONES: LA LLEGADA");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jRetorno.setBackground(new java.awt.Color(255, 0, 0));
        jRetorno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRetorno.setForeground(new java.awt.Color(255, 255, 255));
        jRetorno.setText("REGRESAR AL MENU");
        jRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetornoActionPerformed(evt);
            }
        });
        getContentPane().add(jRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("VENTA DE PRODUCTOS");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        accion.setBackground(new java.awt.Color(51, 51, 255));
        accion.setForeground(new java.awt.Color(255, 255, 255));
        accion.setText("GENERAR VENTA Y FACTURA");
        getContentPane().add(accion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/165961.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 846, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetornoActionPerformed
        accesos2 obj=new accesos2();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jRetornoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JButton accion;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jRetorno;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
